import json

class Report:
    def __init__(self, userName):
        self.name = userName

    def listEmotions(self):
        filename = f"conversations/{self.name}_convo.json"
        with open(filename, 'r') as file:
            data = json.load(file)
        emotions = [x for x in data['Emotion'] if x != 0]
        counts = {}
        for e in emotions:
            if e in counts:
                counts[e] += 1
            else:
                counts[e] = 1
        self.emotions = counts

    def get_emotion_percentage(self):
        total = sum(self.emotions.values())
        percentages = {k: v/total*100 for k, v in self.emotions.items()}
        top_emotion, top_percentage = max(percentages.items(), key=lambda x: x[1])
        # print(f"The top emotion is {top_emotion} with {top_percentage:.2f}%")
        self.top_emotion = top_emotion
        self.top_percentage = top_percentage
        if (top_emotion == 'anger' or top_emotion == 'sadness'or top_emotion == 'fear'):
            self.mood = 'negative'
        elif (top_emotion == 'joy' or top_emotion == 'love'):
            self.mood = 'positive'
    
    def gen_Report(self):
        self.listEmotions()
        self.get_emotion_percentage()
        print(f"Your top emotion is {self.top_emotion} with {self.top_percentage:.2f}%")
        print(f"Your mood is {self.mood}")
        return self.top_emotion, self.mood

    

from fpdf import FPDF

def generate_report_pdf(report):
    # Create a new PDF file with the user's name
    filename = f"{report.name}'s_Sentimental_evaluation_report.pdf"
    pdf = FPDF()
    pdf.add_page()
    
    # Set the font and font size for the title
    pdf.set_font("Arial", "B", size=20)
    
    # Add the title to the PDF
    pdf.cell(0, 20, txt=f"Report for {report.name}", align="C", ln=1)
    
    # Set the font and font size for the section headings
    pdf.set_font("Arial", "B", size=16)
    
    # Add the top emotion section to the PDF
    pdf.cell(0, 10, txt="Top Emotion", ln=1)
    pdf.set_font("Arial", size=12)
    pdf.cell(0, 10, txt=f"{report.name}'s top emotion is {report.top_emotion} with {report.top_percentage:.2f}%", ln=1)
    
    # Set the font and font size for the section headings
    pdf.set_font("Arial", "B", size=16)
    # Add the mood section to the PDF
    pdf.cell(0, 10, txt="Mood", ln=1)
    pdf.set_font("Arial", size=12)
    pdf.cell(0, 10, txt=f"{report.name}'s mood is {report.mood}", ln=1)
    
    # Add the footer to the PDF
    pdf.set_y(-5)
    pdf.set_font("Arial", size=10)
    pdf.cell(0, 10, txt="Generated by Chat With EMMA", align="C")
    
    # Save and close the PDF file
    pdf.output(f'Reports/{filename}')
    
    print(f"Report saved as {filename}")

# report = Report(userName='jenna')
# report.gen_Report()
# generate_report_pdf(report)